### ISSUE TITLE
Compatibility issues with webpack css-loader

### ISSUE THREAD

**Issue by larissa-n** [nadbm/react-datasheet#245]
The latest compatible version of [css-loader](https://www.npmjs.com/package/css-loader) is 2.1.1. For any newer version (starting with 3.0.0; current one is 4.2.2) it throws:

```
ERROR in ./node_modules/react-datasheet/lib/react-datasheet.css (./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/react-datasheet/lib/react-datasheet.css)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'localIdentName'. These properties are valid:
   object { url?, import?, modules?, sourceMap?, importLoaders?, localsConvention?, onlyLocals?, esModule? }
    at validate (~/node_modules/css-loader/node_modules/schema-utils/dist/validate.js:96:11)
    at Object.loader (~/node_modules/css-loader/dist/index.js:36:28)
 @ ./node_modules/react-datasheet/lib/react-datasheet.css 2:14-87 21:1-42:3 22:19-92

```
Are there any plans to upgrade this library? Thank you!

**Comment by larissa-n** [comment]
Any updates (@nadbm)? Thank you!
